export LANG=en_GB.utf8
export GDM_LANG=en_GB.utf8

# Enable instant prompt for Powerlevel10k
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh/scripts/zplug/init.zsh
zplug "wting/autojump", from:github
zplug "elstgav/branch-manager", from:github
zplug "rutchkiwi/copyzshell", from:github
zplug "lukechilds/zsh-nvm", from:github
zplug "lib/completion", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:3
zplug "djui/alias-tips", from:github
zplug load

export ZSH=/usr/share/oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel9k"

# Powerlevel10k - faster fork of Powerlevel9k
source ~/.p10k.zsh

export VISUAL="vim"
export EDITOR="vim"
export XDG_CONFIG_HOME="$HOME/.config"

# Force terminal to use 256 colors, if it can
# Credit: http://www.reddit.com/r/vim/comments/21fo9c/ask_unable_to_set_256_colors_theme_terminal_is/cgd50qm
export TERM=xterm-256color
[[ -n $TMUX ]] && export TERM=screen-256color

COMPLETION_WAITING_DOTS="true"

# don't put duplicate lines in the history. See bash(1) for more options
# Lines which begin with a space character are no saved in the history list
# All previous lines matching the current line will be removed from history
export HISTCONTROL=ignoredups:ignorespace:erasedups

export PATH="$PATH:$HOME/.local/bin"

# Source aliases
source $HOME/.zsh_aliases

# Source functions
source $HOME/.zsh_functions

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Let tmux grab the working directory
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

# rbenv
export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(rbenv init -)"
rbenv shell 2.4.2

# Source autojump
source /usr/share/autojump/autojump.zsh

[ -s "/$HOME/.scm_breeze/scm_breeze.sh" ] && source "/$HOME/.scm_breeze/scm_breeze.sh"

# Activate thefuck
eval "$(thefuck --alias)"

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use
# Load nvm bash_completion
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Activate OMZ
source $ZSH/oh-my-zsh.sh

# Activate fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Exercism autocomplete
if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

# Import any settings local to this machine
source $HOME/.zsh_local
