export LANG=en_GB.utf8
export GDM_LANG=en_GB.utf8

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Antigen
source $HOME/dotfiles/zsh/antigen/antigen.zsh
export ANTIGEN_DEFAULT_REPO_URL=git@github.com:countjocular/oh-my-zsh.git
antigen-use oh-my-zsh
antigen-bundle git
antigen-bundle heroku
antigen-bundle command-not-found
antigen-bundle gem
antigen-bundle git-flow
antigen-bundle rails
antigen-bundle rails3
antigen-bundle rake
antigen-bundle ruby
antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-bundle colored-man
antigen-theme countjocular_fat
antigen-apply

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Base16 Shell
BASE16_SCHEME="tomorrow"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Force terminal to use 256 colors, if it can
export TERM="xterm-256color"

COMPLETION_WAITING_DOTS="true"

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# Source aliases
source $HOME/.zsh_aliases

# Source functions
source $HOME/.zsh_functions


export EDITOR=vim

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Let tmux grab the working directory
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

export PATH=$PATH:$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh 
chruby ruby-2.0

# Source autojump
. /usr/share/autojump/autojump.sh

[ -s "/$HOME/.scm_breeze/scm_breeze.sh" ] && source "/$HOME/.scm_breeze/scm_breeze.sh"

# Set Base16 Shell colors
BASE16_SCHEME="tomorrow"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Import any settings local to this machine
source $HOME/.zsh_local
