export LANG=en_GB.utf8
export GDM_LANG=en_GB.utf8

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Antigen
source $HOME/dotfiles/zsh/antigen/antigen.zsh
export ANTIGEN_DEFAULT_REPO_URL=git@github.com:countjocular/oh-my-zsh.git
antigen-use oh-my-zsh
antigen-bundle git
antigen bundle lukechilds/zsh-nvm
antigen-bundle command-not-found
antigen-bundle gem
antigen-bundle git-flow
antigen-bundle rails
antigen-bundle rake
antigen-bundle ruby
antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-bundle colored-man-pages
antigen-bundle archlinux
antigen-theme countjocular_fat
antigen-apply

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"
#
export VISUAL="vim"
export XDG_CONFIG_HOME="$HOME/.config"

# Base16 Shell
BASE16_SCHEME="chalk"
BASE16_SHELL="$HOME/dotfiles/zsh/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Force terminal to use 256 colors, if it can
# Credit: http://www.reddit.com/r/vim/comments/21fo9c/ask_unable_to_set_256_colors_theme_terminal_is/cgd50qm
export TERM=xterm-256color
[[ -n $TMUX ]] && export TERM=screen-256color

COMPLETION_WAITING_DOTS="true"

# don't put duplicate lines in the history. See bash(1) for more options
# Lines which begin with a space character are no saved in the history list
# All previous lines matching the current line will be removed from history
export HISTCONTROL=ignoredups:ignorespace:erasedups

# Source aliases
source $HOME/.zsh_aliases

# Source functions
source $HOME/.zsh_functions


export EDITOR=vim

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# Let tmux grab the working directory
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

export PATH=$PATH:$HOME/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/sbin:/bin:/usr/games

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
rbenv shell 2.1.1

# Source autojump
#. /usr/bin/autojump

[ -s "/$HOME/.scm_breeze/scm_breeze.sh" ] && source "/$HOME/.scm_breeze/scm_breeze.sh"

# pm project switcher
source ~/.pm/pm.zsh
alias pma="pm add"
alias pmg="pm go"
alias pmrm="pm remove"
alias pml="pm list"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Activate thefuck
eval "$(thefuck --alias)"

# Temporary fix for "GREP_OPTIONS is deprecated" warning.
# See https://github.com/robbyrussell/oh-my-zsh/pull/3341
alias grep="grep ${GREP_OPTIONS}"
unset GREP_OPTIONS
source /usr/share/nvm/init-nvm.sh

# Import any settings local to this machine
source $HOME/.zsh_local

